FROM ubuntu:bionic
MAINTAINER Leonid Myravjev <asm@asm.pp.ru>

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git vim curl gnupg2 ca-certificates python python-dev net-tools

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sqlite3

WORKDIR /opt/shinobi.git
RUN git clone https://gitlab.com/Shinobi-Systems/Shinobi.git .

ADD scripts/sudo /bin/sudo
#ADD scripts/inst.sh inst.sh
#RUN inst.sh


